"""Add Department model and department_id to Section

Revision ID: 113abf13ffef
Revises: a1b2c3d4e5f6
Create Date: 2026-07-08 18:07:09.583568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113abf13ffef'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_department_school_code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('ix_department_school', ['school_id'], unique=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_section_department', ['department_id'], unique=False)
        batch_op.create_foreign_key('fk_section_department', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_section_department', type_='foreignkey')
        batch_op.drop_index('ix_section_department')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index('ix_department_school')

    op.drop_table('departments')
    # ### end Alembic commands ###
