"""add conflict strategy and counts to ImportBatch

Revision ID: 27935e2c156e
Revises: c7f5e17505b1
Create Date: 2026-07-09 10:09:37.649704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27935e2c156e'
down_revision = 'c7f5e17505b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conflict_strategy', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_column('conflict_strategy')
        batch_op.drop_column('updated_count')
        batch_op.drop_column('skipped_count')

    # ### end Alembic commands ###
