"""Add PluginState model

Revision ID: 475386ebc68a
Revises: 40e3ba5f3703
Create Date: 2026-07-08 10:28:43.787231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475386ebc68a'
down_revision = '40e3ba5f3703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugin_states')
    # ### end Alembic commands ###
