"""add site_settings table

Revision ID: 787fdb4dae06
Revises: 9c205c50d7b5
Create Date: 2026-07-07 22:59:56.662250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787fdb4dae06'
down_revision = '9c205c50d7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
