"""add academic_years table

Revision ID: a04c93c73c47
Revises: 787fdb4dae06
Create Date: 2026-07-07 23:18:27.151283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04c93c73c47'
down_revision = '787fdb4dae06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_academic_year_name')
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index('ix_academic_year_institution', ['institution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index('ix_academic_year_institution')

    op.drop_table('academic_years')
    # ### end Alembic commands ###
